{
 "title": "printwiz",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Y Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "controller_target_y - printer_y",
     "legendFormat": "Y Error"
    }
   ]
  },
  {
   "title": "X Location and Target",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "printer_x", "legendFormat": "X True" },
    { "expr": "controller_target_x", "legendFormat": "X Target" }
   ]
  },
  {
   "title": "Sensors X",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "printer_x", "legendFormat": "True" },
    { "expr": "sensor_good_x", "legendFormat": "Sensor - Good" },
    { "expr": "sensor_ok_x", "legendFormat": "Sensor - Ok" },
    { "expr": "sensor_bad_x", "legendFormat": "Sensor - Bad" }
   ]
  },
  {
   "title": "Y Location and Target",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "printer_y", "legendFormat": "Y True" },
    { "expr": "controller_target_y", "legendFormat": "Y Target" }
   ]
  },
  {
   "title": "Sensors Y",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "printer_y", "legendFormat": "True" },
    { "expr": "sensor_good_y", "legendFormat": "Sensor - Good" },
    { "expr": "sensor_ok_y", "legendFormat": "Sensor - Ok" },
    { "expr": "sensor_bad_y", "legendFormat": "Sensor - Bad" }
   ]
  },
  {
   "title": "Z Location and Target",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "printer_z", "legendFormat": "Z True" },
    { "expr": "controller_target_z", "legendFormat": "Z Target" }
   ]
  },
  {
   "title": "Sensor Z",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "printer_z", "legendFormat": "True" },
    { "expr": "sensor_good_z", "legendFormat": "Sensor - Good" },
    { "expr": "sensor_ok_z", "legendFormat": "Sensor - Ok" },
    { "expr": "sensor_bad_z", "legendFormat": "Sensor - Bad" }
   ]
  }
 ]
}